<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.eletra</groupId>
    <artifactId>projeto-integracao-frontend</artifactId>
    <version>0.2.0</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.6.0</version>
                <configuration>
                    <mainClass>com.eletra.Main</mainClass>
                    <verbose>true</verbose>
                    <vendor>Jhonatan</vendor>
                    <bundleArguments>
                        <win.console>true</win.console>
                        <identifier>UPDATE-DETECTION</identifier>
                        <installdirChooser>true</installdirChooser>
                    </bundleArguments>
                    <additionalAppResources>${project.basedir}/src/main/resources</additionalAppResources>
                </configuration>
                <executions>
                    <execution>
                        <id>create-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.eletra</groupId>
            <artifactId>projeto-integracao-backend</artifactId>
            <version>0.2.0</version>
        </dependency>
    </dependencies>

</project>